services:
  manager:
    image: manager:latest
    container_name: manager
    ports:
      - 8002:8000
    env_file: ./manager/.env
    networks:
      - backend
    healthcheck:
      test: "curl --fail --silent localhost:8000/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 2s
      start_interval: 30s
      retries: 10

  worker:
    image: worker:latest
    env_file: ./worker/.env
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      manager:
        condition: service_healthy

networks:
  backend:
    driver: bridge
