spring:
  config:
    import: file:.env[.properties]
  application:
    name: manager
  worker:
    workers-count: ${WORKERS_COUNT}
    worker-service-domain-name: ${WORKER_SERVICE_DOMAIN_NAME}
  request:
    expiration-time: ${REQUEST_EXPIRATION_TIME}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: ${SERVER_PORT}
springdoc:
  swagger-ui:
    path: /docs

