spring:
  application:
    name: manager
  worker:
    port: ${WORKER_SERVICE_PORT}
    api-path: ${WORKER_API_PATH}
    endpoints:
      task: ${WORKER_TASK_ENDPOINT}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoint:
    health:
      show-details: never

server:
  port: ${SERVER_PORT}
springdoc:
  swagger-ui:
    path: /docs

