spring:
  application:
    name: manager
  worker:
    port: ${WORKER_SERVICE_PORT}
    api-path: ${WORKER_API_PATH}
    endpoints:
      task: ${WORKER_TASK_ENDPOINT}
  data:
    mongodb:
      uri: mongodb://${MONGO_R0_HOST}:${MONGO_R0_PORT},${MONGO_R1_HOST}:${MONGO_R1_PORT},${MONGO_R2_HOST}:${MONGO_R2_PORT}/${MONGO_DATABASE}?replicaSet=rs0
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      direct:
        prefetch: 1
      simple:
        prefetch: 1

management:
  endpoint:
    health:
      show-details: never

server:
  port: ${SERVER_PORT}
springdoc:
  swagger-ui:
    path: /docs


#mongodb://{MONGO_USERNAME}:{MONGO_PASSWORD}@{MONGO_R0_HOST}:{MONGO_R0_PORT},{MONGO_R1_HOST}:{MONGO_R1_PORT},{MONGO_R2_HOST}:{MONGO_R2_PORT}/{MONGO_DATABASE}

#mongodb://user:123321@127.0.0.1:27016,127.0.0.1:27018,127.0.0.1:27019/crackhash